@startuml
left to right direction
actor Admin as u


package "MyShop" {
  usecase "Authentication" as UC1
  usecase "Management interface" as UC2
  usecase "Users management" as UC3
  usecase "Products management" as UC4
}

u --> UC1
u --> UC2
u --> UC3
u --> UC4

@enduml
