@startuml
left to right direction
actor User as u


package "MyShop" {
  usecase "Authentication" as UC1
  usecase "Browse Products" as UC2
  usecase "Product detail view" as UC3
  usecase "Add Product to Cart" as UC4
  usecase "Remove Product from Cart" as UC5

}

u --> UC1
u --> UC2
u --> UC3
u --> UC4
u --> UC5

@enduml
